[logger]
environment="dev"

[server]
host="0.0.0.0"
port=8080

[llm]
name="mistral-7b-openorca.Q2_K.gguf"
n_ctx=2048
n_threads=16

[s3]
bucket="machanirobotics-models"
root_path="llm/gguf"

[embed]
name="BAAI/bge-large-en"