[logger]
environment="dev"

[server]
host="0.0.0.0"
port=8080

[llm]
multimodal=true
name="ggml_llava-v1.5-7b"
n_ctx=2048
n_threads=16
quantization="q4_k"

[s3]
bucket="machanirobotics-models"
root_path="llm/gguf"

[embed]
name="BAAI/bge-large-en"